package task_management_system;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Student.Admin
 */
public class task_management_system extends javax.swing.JFrame {

    /**
     * Creates new form Register_student
     */
    public task_management_system() {
        initComponents();
        this.setTitle("Home");
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        educator_login = new javax.swing.JButton();
        scholar_login = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(117, 98, 122));
        jLabel3.setText("tms");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 180, 130, 80);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(93, 78, 98));
        jLabel4.setText("tms");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 30, 60, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(93, 78, 98));
        jLabel5.setText("ABOUT");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(550, 30, 180, 30);

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(117, 98, 122));
        jLabel6.setText("organized.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 360, 490, 30);

        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(117, 98, 122));
        jLabel8.setText("The very first task management system of Passerelles Numeriques Philippines.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 260, 490, 30);

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(117, 98, 122));
        jLabel7.setText("This is an application specially built to keep track of errands or");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 280, 490, 30);

        jLabel9.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(117, 98, 122));
        jLabel9.setText("tasks that are needed to be done by the scholars. This application will be ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 300, 490, 30);

        jLabel10.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(117, 98, 122));
        jLabel10.setText("like a task keeper where the educator would be able to enter the tasks that ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 320, 490, 30);

        jLabel11.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(117, 98, 122));
        jLabel11.setText("the scholar needs to do allowig scholars to be more productive and ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 340, 490, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(117, 98, 122));
        jLabel12.setText("Welcome to,");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(60, 160, 180, 30);

        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(117, 98, 122));
        jButton1.setText("EDUCATOR");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(760, 20, 120, 40);

        jButton2.setBackground(new java.awt.Color(117, 98, 122));
        jButton2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SCHOLAR");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(900, 20, 120, 40);

        educator_login.setFont(new java.awt.Font("Segoe UI Emoji", 1, 15)); // NOI18N
        educator_login.setForeground(new java.awt.Color(117, 98, 122));
        educator_login.setText("EDUCATOR");
        educator_login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        educator_login.setBorderPainted(false);
        educator_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        educator_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                educator_loginActionPerformed(evt);
            }
        });
        jPanel1.add(educator_login);
        educator_login.setBounds(60, 450, 120, 40);

        scholar_login.setBackground(new java.awt.Color(117, 98, 122));
        scholar_login.setFont(new java.awt.Font("Segoe UI Emoji", 1, 15)); // NOI18N
        scholar_login.setForeground(new java.awt.Color(255, 255, 255));
        scholar_login.setText("SCHOLAR");
        scholar_login.setBorder(null);
        scholar_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scholar_loginActionPerformed(evt);
            }
        });
        jPanel1.add(scholar_login);
        scholar_login.setBounds(200, 450, 120, 40);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(117, 98, 122));
        jLabel13.setText("CHOOSE A ROLE:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(60, 410, 180, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(93, 78, 98));
        jLabel14.setText("CREATORS");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(400, 30, 180, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Task-amico 1.png"))); // NOI18N
        jLabel2.setIconTextGap(1);
        jLabel2.setMaximumSize(new java.awt.Dimension(650, 500));
        jLabel2.setMinimumSize(new java.awt.Dimension(135, 675));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(450, 60, 700, 660);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image 1.png"))); // NOI18N
        background.setText("jLabel1");
        jPanel1.add(background);
        background.setBounds(-40, -420, 2500, 1400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1053, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoginForm_educator log_educ = new LoginForm_educator();
        log_educ.pack();
        log_educ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void educator_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_educator_loginActionPerformed

        LoginForm_educator log_educ = new LoginForm_educator();
        log_educ.pack();
        log_educ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_educator_loginActionPerformed

    private void scholar_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scholar_loginActionPerformed

        LoginForm_student log_scholar = new LoginForm_student();
        log_scholar.pack();
        log_scholar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_scholar_loginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoginForm_student log_scholar = new LoginForm_student();
        log_scholar.pack();
        log_scholar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new task_management_system().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton educator_login;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton scholar_login;
    // End of variables declaration//GEN-END:variables
}
